apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "horovod.fullname" . }}
  labels:
    app: {{ template "horovod.name" . }}
    chart: {{ template "horovod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: worker
spec:
  selector:
    matchLabels:
      app: {{ template "horovod.name" . }}
      chart: {{ template "horovod.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: worker
  serviceName: {{ template "horovod.fullname" . }}
  podManagementPolicy: {{ .Values.worker.podManagementPolicy }}
  replicas: {{ .Values.workersCount }}
  template:
    metadata:
      labels:
        app: {{ template "horovod.name" . }}
        chart: {{ template "horovod.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: worker
        runName: {{ .Release.Name }}
      annotations:
        scheduling.k8s.io/group-name: {{ .Release.Name }}-podgroup
    spec:
      schedulerName: kube-batch
      {{- if .Values.useHostNetwork }}
      hostNetwork: {{ .Values.useHostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- if .Values.useHostPID }}
      hostPID: {{ .Values.useHostPID }}
      {{- end }}
      volumes:
      - name: {{ template "horovod.fullname" . }}-cm
        configMap:
          name: {{ template "horovod.fullname" . }}
          items:
          - key: hostfile.config
            path: hostfile
            mode: 438
          - key: ssh.readiness
            path: check.sh
            mode: 365
          - key: worker.run
            path: run.sh
            mode: 365
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent  6 }}
{{- end }}
      containers:
      - name: worker
        image: "{{ .Values.image.clusterRepository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SSHPORT
          value: "{{ .Values.ssh.port }}"
       {{- if .Values.ssh.useSecrets }}
        - name: USESECRETS
          value: "{{ .Values.ssh.useSecrets }}"
       {{- end }}
{{- if .Values.worker.env }}
{{ toYaml .Values.worker.env | indent 8 }}
{{- end }}
{{- if .Values.worker.privileged }}
        securityContext:
          privileged: true
{{- end }}
        ports:
        - containerPort: {{ .Values.ssh.port }}
      {{- if .Values.useHostNetwork }}
          hostPort:  {{ .Values.ssh.port }}
      {{- end }}
        volumeMounts:
        - name: {{ template "horovod.fullname" . }}-cm
          mountPath: /horovod/generated
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 8 }}
{{- end }}
        - name: output-home
          mountPath: /mnt/output/experiment
          subPath: {{ .Release.Name }}
        command:
        - /horovod/generated/run.sh
{{- if .Values.ssh.useSecrets }}
        readinessProbe:
          exec:
            command:
            - /horovod/generated/check.sh
          initialDelaySeconds: 1
          periodSeconds: 2
{{- end }}
        resources:
          requests:
            cpu: {{ default .Values.resources.requests.cpu .Values.cpu}}
            memory: {{ default .Values.resources.requests.memory .Values.memory }}
          limits:
            cpu: {{ default .Values.resources.limits.cpu .Values.cpu }}
            memory: {{ default .Values.resources.limits.memory .Values.memory }}