apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart_version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    runName: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  resourceNames:
  - "{{ .Release.Name }}"
  verbs:
  - "get"
- apiGroups:
  - ""
  resources:
  - "services/proxy"
  resourceNames:
  - "{{ .Release.Name }}:rest-port"
  verbs:
  - "get"
  - "create"